### PR TITLE
Add instructions to build kos image manually

### PR DESCRIPTION
**Pull request by behouba**
Added instruction to build kos image manually with eventully executable files. 
We will need to have executor entity ready for kos for the this to be complete. 
Let try to build the image with executor inside manually for now. 
After that, I think it will be more easier to write the script to implement the `builder interface` for kos inside: `pkg/build/kos.go`

### CODE REVIEW

**Comment by FahimaGold** [comment]
I have already done the first part of the executor, it is under the branch: Kos-executor

**Comment by behouba** [comment]
Great @FahimaGold ! I deleted this PR, Because I have activated github actions and I have to fix some stuff

**Comment by behouba** [comment]
After that, we will I help you to finish `executor` because I need it working to advance on HostFuzzer.

**Comment by behouba** [comment]
We will now have some trouble with Ci ). They are very strict rules here

**Comment by FahimaGold** [comment]
Thanks for GitHub actions,i have just started that lab 😅 for the
executor,i did the part that initializes the process,we still need the part
that executes syscalls...

**Comment by behouba** [comment]
That's great!

**Pull request closed without merging**
